baseURL = "http://isaiah.kriegman.net/"
languageCode = "en-us"
title = "Isaiah Kriegman"
theme = "k.cc"
[params] 
    author = "Isaiah Kriegman"
    favicon = "/favicon.ico"

[markup.highlight]
style = "dracula"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
